version: '3.8'

services:
  backend:
    build: ./backend
    container_name: fastapi-backend
    volumes:
      - ./backend:/app
    ports:
      - "8082:8082"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5434/postgres
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: vue-frontend
    ports:
      - "8002:8002"
    depends_on:
      - backend

  db:
    image: postgres:14
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: appsecret
      POSTGRES_DB: appdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5434:5434"

volumes:
  postgres-data:
